# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - type: volume
        source: nearby-nosh-db-volume
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  nearby-nosh-db-volume:
